### ISSUE TITLE
IntegrityError at /vre-api-test/api/workflows/

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/VREPaaS#116]
When we start VRE and open the API from the browser at :vre-api-test/api/workflows/ we get the following error:

```python
Environment:


Request Method: GET
Request URL: http://localhost:8000/vre-api-test/api/workflows/

Django Version: 4.0.10
Python Version: 3.11.3
Installed Applications:
['cells',
 'workflows',
 'virtual_labs',
 'data_products',
 'rest_framework',
 'rest_framework_gis',
 'corsheaders',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.gis']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django-keycloak-auth.middleware.KeycloakMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

The above exception (update or delete on table "workflows_workflow" violates foreign key constraint "data_products_datapr_workflow_id_4d36ce10_fk_workflows" on table "data_products_dataproduct"
DETAIL:  Key (argo_id)=(n-a-a-vre-dev-skoulouzis-6zvkb) is still referenced from table "data_products_dataproduct".
) was the direct cause of the following exception:
  File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/workflows/views.py", line 98, in list
    wf_serializer.save()
  File "/app/workflows/serializers.py", line 10, in save
    return super().save(**kwargs)
  File "/opt/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 726, in save
    self.instance = self.update(self.instance, validated_data)
  File "/app/workflows/serializers.py", line 29, in update
    workflow.delete()
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1094, in delete
    return collector.delete()
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/deletion.py", line 446, in delete
    count = sql.DeleteQuery(model).delete_batch(
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/sql/subqueries.py", line 42, in delete_batch
    num_deleted += self.do_query(
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/sql/subqueries.py", line 20, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /vre-api-test/api/workflows/
Exception Value: update or delete on table "workflows_workflow" violates foreign key constraint "data_products_datapr_workflow_id_4d36ce10_fk_workflows" on table "data_products_dataproduct"
DETAIL:  Key (argo_id)=(n-a-a-vre-dev-skoulouzis-6zvkb) is still referenced from table "data_products_dataproduct".



```

**Comment by skoulouzis** [comment]
We manually triggered an update in Tilt for the DB and API and get the same error

**Comment by gpelouze** [comment]
Fixed by https://github.com/QCDIS/VREPaaS/issues/159
